// Generated by CoffeeScript 1.9.3
module.exports = {
  entry: {
    colorpicker: ['./src/main.cjsx']
  },
  output: {
    path: './lib/',
    filename: 'bundle.js'
  },
  devtool: 'eval',
  module: {
    loaders: [
      {
        test: /\.cjsx$/,
        loaders: ['coffee', 'cjsx']
      }, {
        test: /\.coffee$/,
        loader: 'coffee'
      }
    ]
  },
  resolve: {
    root: '/',
    extensions: ['', '.js', '.coffee', '.cjsx']
  }
};
